"""Compare APS, RAPS, SAPS, and RANK conformal prediction on NYVEST.

Uses cached XGBoost softmax probabilities from `reports/saps_cache.npz`
(generated by conformal_saps.py on first run). Calibrates each method on the
val split and evaluates on test; reports marginal coverage and prediction-set
size statistics.

Methods:
  APS  — Romano et al. 2020. V(p,k) = sum_{j<r} p_(j) + u * p_(r).
  RAPS — Angelopoulos et al. 2021. V_APS + lam_reg * max(0, r - k_reg).
  SAPS — Huang et al. 2024. V = p_(1)*u if r=1 else p_(1) + (r-2+u)*lam.
  RANK — Liu et al. 2025 (Pattern Recognition, arXiv 2407.04407). Two-stage:
         find r*_alpha = ⌊(n+1)α⌋-th largest true-class rank in cal; include
         top-r*_α classes iff the sample's rank-r*_α prob is in the top-p
         fraction of cal rank-r*_α probs, else top-(r*_α - 1).

Usage:
    ~/myprojects/recover/.venv/bin/python scripts/conformal_compare.py
    ~/myprojects/recover/.venv/bin/python scripts/conformal_compare.py --alpha 0.05,0.1,0.2
"""

from __future__ import annotations

import argparse
import os
import time
from pathlib import Path

import numpy as np
import pandas as pd

from benchmark_tabular import get_data_dir, load_split, resolve_device
from conformal_saps import fit_base_model, saps_scores, saps_cal_scores, conformal_quantile, evaluate_sets


# ---------- shared helpers ----------

def _ranks_and_sorted(probs: np.ndarray):
    """Return (ranks, order, sorted_probs) for probs (n, C).

    ranks[i, k]      = 1-indexed rank of class k for sample i (rank 1 = largest prob)
    order[i, :]      = class indices in descending-prob order
    sorted_probs[i,:] = probs sorted descending along axis 1
    """
    n, C = probs.shape
    order = np.argsort(-probs, axis=1)
    sorted_probs = np.take_along_axis(probs, order, axis=1)
    ranks = np.empty_like(order)
    row = np.arange(n)[:, None]
    ranks[row, order] = np.arange(1, C + 1)[None, :]
    return ranks, order, sorted_probs


# ---------- APS ----------

def _aps_scores(probs: np.ndarray, u: np.ndarray, lam_reg: float = 0.0, k_reg: int = 1) -> np.ndarray:
    """APS / RAPS score for every (sample, class). lam_reg=0 → plain APS."""
    ranks, order, sorted_probs = _ranks_and_sorted(probs)
    n, C = probs.shape
    cumsum_sorted = np.cumsum(sorted_probs, axis=1)          # cum through rank r, i.e. includes p_(r)
    cumsum_before_rank = np.concatenate(
        [np.zeros((n, 1), dtype=sorted_probs.dtype), cumsum_sorted[:, :-1]], axis=1
    )                                                         # sum of p_(1..r-1)
    # cumsum_before_rank[i, r-1] is cum through rank r-1 in sorted order.
    # We need to place this value back at each class's position using its rank.
    cum_at_class = np.take_along_axis(cumsum_before_rank, ranks - 1, axis=1)
    scores = cum_at_class + u[:, None] * probs
    if lam_reg > 0:
        scores = scores + lam_reg * np.maximum(0, ranks - k_reg)
    return scores


def _aps_cal_scores(probs, y, u, lam_reg=0.0, k_reg=1):
    C = probs.shape[1]
    allscores = _aps_scores(probs, u, lam_reg=lam_reg, k_reg=k_reg)
    return allscores[np.arange(len(y)), y]


def run_aps_like(probs_cal, y_cal, probs_test, y_test, u_cal, u_test,
                 alpha, lam_reg=0.0, k_reg=1):
    cal_s = _aps_cal_scores(probs_cal, y_cal, u_cal, lam_reg=lam_reg, k_reg=k_reg)
    tau = conformal_quantile(cal_s, alpha)
    all_s = _aps_scores(probs_test, u_test, lam_reg=lam_reg, k_reg=k_reg)
    sets = all_s <= tau
    return _set_metrics(sets, y_test, tau)


# ---------- RANK (two-stage Algorithm 1 from the paper) ----------

def run_rank(probs_cal, y_cal, probs_test, y_test, alpha):
    """Two-stage rank-based CP (Liu et al. 2025, Algorithm 1)."""
    n, C = probs_cal.shape
    ranks_cal, _, _ = _ranks_and_sorted(probs_cal)
    r_true = ranks_cal[np.arange(n), y_cal]                 # rank of true class per cal sample
    # r*_α = ⌊(n+1)α⌋-th LARGEST rank (paper notation).
    kth = int(np.floor((n + 1) * alpha))
    kth = max(1, min(kth, n))
    r_sorted_desc = np.sort(r_true)[::-1]
    r_star = int(r_sorted_desc[kth - 1])

    count_below = int(np.sum(r_true <= r_star - 1))
    count_at = int(np.sum(r_true == r_star))
    if count_at == 0:
        # No boundary cohort — just use top-r*_α classes everywhere.
        use_rstar_threshold = -np.inf
    else:
        p_prop = (n - int(np.floor((n + 1) * alpha)) - count_below) / count_at
        p_prop = float(np.clip(p_prop, 0.0, 1.0))
        # π* = ⌈n·p⌉-th largest of {π̂_{(r*_α)}(x_i)} over cal samples.
        sorted_probs_cal = np.sort(probs_cal, axis=1)[:, ::-1]   # (n, C) descending
        rstar_probs = sorted_probs_cal[:, r_star - 1]            # prob at rank r*_α per cal sample
        k_pick = int(np.ceil(n * p_prop))
        if k_pick <= 0:
            use_rstar_threshold = np.inf                         # never include r*_α level
        elif k_pick > len(rstar_probs):
            use_rstar_threshold = -np.inf
        else:
            use_rstar_threshold = float(np.sort(rstar_probs)[::-1][k_pick - 1])

    # Test-time set construction.
    nt, _ = probs_test.shape
    ranks_test, _, sorted_test = _ranks_and_sorted(probs_test)
    # For each test sample: if p_(r*_α)(x) >= π*, include top-r*_α; else top-(r*_α - 1).
    rstar_prob_test = sorted_test[:, r_star - 1] if r_star >= 1 else np.zeros(nt)
    include_rstar = rstar_prob_test >= use_rstar_threshold
    size_per_sample = np.where(include_rstar, r_star, max(r_star - 1, 0))
    sets = ranks_test <= size_per_sample[:, None]

    return {**_set_metrics(sets, y_test, np.nan),
            "r_star": r_star, "p_at_rstar": (count_below, count_at, n)}


# ---------- shared metric helper ----------

def _set_metrics(sets: np.ndarray, y: np.ndarray, tau: float) -> dict:
    set_sizes = sets.sum(axis=1)
    covered = sets[np.arange(len(y)), y]
    return {
        "tau": float(tau) if np.isfinite(tau) else np.nan,
        "coverage": float(covered.mean()),
        "avg_set_size": float(set_sizes.mean()),
        "median_set_size": float(np.median(set_sizes)),
        "max_set_size": int(set_sizes.max()),
        "pct_singleton": float((set_sizes == 1).mean()),
        "pct_empty": float((set_sizes == 0).mean()),
    }


def run_saps(probs_cal, y_cal, probs_test, y_test, u_cal, u_test, alpha, lam):
    cal_s = saps_cal_scores(probs_cal, y_cal, u_cal, lam)
    tau = conformal_quantile(cal_s, alpha)
    test_scores = saps_scores(probs_test, np.arange(probs_test.shape[1]), u_test, lam)
    sets = test_scores <= tau
    return _set_metrics(sets, y_test, tau)


# ---------- main ----------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--alpha", default="0.05,0.1,0.2",
                        help="Miscoverage levels; comma-separated.")
    parser.add_argument("--saps-lam", type=float, default=0.2,
                        help="SAPS penalty (Pareto value from SAPS sweep).")
    parser.add_argument("--raps-lam", type=float, default=0.01,
                        help="RAPS regularization weight.")
    parser.add_argument("--raps-kreg", type=int, default=1,
                        help="RAPS k_reg (sets up to this rank are unpenalised).")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--deterministic", action="store_true",
                        help="u=1 instead of U(0,1). Applies to APS/RAPS/SAPS.")
    parser.add_argument("--n-estimators", type=int, default=500)
    parser.add_argument("--n-jobs", type=int, default=max(1, (os.cpu_count() or 4) // 2))
    parser.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--refit", action="store_true")
    args = parser.parse_args()

    device = resolve_device(args.device)
    alphas = [float(a) for a in args.alpha.split(",") if a.strip()]

    data_dir = get_data_dir()
    print(f"Loading data from {data_dir} ...")
    X_train, y_train_raw = load_split("train")
    X_val, y_val_raw = load_split("val")
    X_test, y_test_raw = load_split("test")

    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder().fit(
        pd.concat([y_train_raw, y_val_raw, y_test_raw], ignore_index=True)
    )
    y_train = le.transform(y_train_raw)
    y_val = le.transform(y_val_raw)
    y_test = le.transform(y_test_raw)
    n_classes = len(le.classes_)
    print(f"  train: {len(X_train)}  val: {len(X_val)}  test: {len(X_test)}  classes: {n_classes}")

    cache_path = Path(__file__).parent.parent / "reports" / "saps_cache.npz"
    val_probs, test_probs = fit_base_model(
        X_train, y_train, X_val, X_test,
        n_estimators=args.n_estimators, n_jobs=args.n_jobs, device=device,
        seed=args.seed, cache_path=cache_path, refit=args.refit,
    )

    rng = np.random.default_rng(args.seed)
    if args.deterministic:
        u_cal = np.ones(len(y_val))
        u_test = np.ones(len(y_test))
    else:
        u_cal = rng.uniform(size=len(y_val))
        u_test = rng.uniform(size=len(y_test))

    rows = []
    for alpha in alphas:
        print(f"\n--- alpha={alpha} (target coverage {1-alpha:.2f}) ---")
        t0 = time.perf_counter()
        res_aps = run_aps_like(val_probs, y_val, test_probs, y_test, u_cal, u_test, alpha)
        t_aps = time.perf_counter() - t0

        t0 = time.perf_counter()
        res_raps = run_aps_like(val_probs, y_val, test_probs, y_test, u_cal, u_test, alpha,
                                lam_reg=args.raps_lam, k_reg=args.raps_kreg)
        t_raps = time.perf_counter() - t0

        t0 = time.perf_counter()
        res_saps = run_saps(val_probs, y_val, test_probs, y_test, u_cal, u_test, alpha, args.saps_lam)
        t_saps = time.perf_counter() - t0

        t0 = time.perf_counter()
        res_rank = run_rank(val_probs, y_val, test_probs, y_test, alpha)
        t_rank = time.perf_counter() - t0

        for method, res, tsec, hp in [
            ("APS",  res_aps,  t_aps,  {}),
            ("RAPS", res_raps, t_raps, {"lam": args.raps_lam, "k_reg": args.raps_kreg}),
            ("SAPS", res_saps, t_saps, {"lam": args.saps_lam}),
            ("RANK", res_rank, t_rank, {"r_star": res_rank.get("r_star")}),
        ]:
            hp_str = " ".join(f"{k}={v}" for k, v in hp.items())
            print(
                f"{method:>5s} cov={res['coverage']:.3f} avg_size={res['avg_set_size']:.2f} "
                f"median={res['median_set_size']:.0f} singleton={res['pct_singleton']:.2f} "
                f"empty={res['pct_empty']:.3f} time={tsec*1000:.0f}ms  {hp_str}"
            )
            rows.append({
                "method": method, "alpha": alpha, "target_coverage": round(1 - alpha, 3),
                "coverage": round(res['coverage'], 4),
                "avg_set_size": round(res['avg_set_size'], 3),
                "median_set_size": int(res['median_set_size']),
                "max_set_size": int(res['max_set_size']),
                "pct_singleton": round(res['pct_singleton'], 4),
                "pct_empty": round(res['pct_empty'], 4),
                "time_ms": round(tsec * 1000, 1),
                **{f"hp_{k}": v for k, v in hp.items()},
            })

    df = pd.DataFrame(rows)
    out = Path(__file__).parent.parent / "reports" / "conformal_compare_results.csv"
    df.to_csv(out, index=False)
    print(f"\nSaved {len(df)} rows to {out}")


if __name__ == "__main__":
    main()
